
CREATE TABLE [dbo].[Products]
(
	[Id]					INT				IDENTITY(1,1) NOT NULL,
	[TypeId]				INT				Not NULL,
	[ProductGenCategoryId]			INT				NULL,
	[CategoryId]			INT				NULL,
	[DesignerId]			INT				NULL,
	[EditId]				INT				NULL,
	[Name]					NVARCHAR(300)	NOT NULL,
	[Price]					NVARCHAR(300)	NULL,
	[Size]					NVARCHAR(300)	NOT NULL,
	[InternationalSize]		NVARCHAR(300)	NULL,
	[Brand]					NVARCHAR(300)	NOT NULL,
	[Color]					NVARCHAR(300)	NOT NULL,
	[Condition]				NVARCHAR(300)	NOT NULL,
	[SellPrice]				NVARCHAR(300)	NULL,
	[RentPrice4Days]		NVARCHAR(300)	NULL,
	[RentPrice8Days]		NVARCHAR(300)	NULL,
	[RentPrice16Days]		NVARCHAR(300)	NULL,
	[RentPrice30Days]		NVARCHAR(300)	NULL,
	[RRP]					NVARCHAR(300)	NOT NULL,
	[Code]					NVARCHAR(300)	NOT NULL,	
	[Details]				NVARCHAR(MAX)	NOT NULL,	
	[IsEBayStore]			BIT				CONSTRAINT [DF_Product_IsEBayStore] DEFAULT (0) NOT NULL,
	[Deleted]				BIT				CONSTRAINT [DF_Product_IsDeleted] DEFAULT (0) NOT NULL,
	[IsAvailable]			BIT				CONSTRAINT [DF_Product_IsAvailable] DEFAULT (1) NOT NULL,
	[CreatedDate]			DATETIMEOFFSET	CONSTRAINT [DF_Product_Created] DEFAULT (GETUTCDATE()) NOT NULL,	
	[ModifiedDate]			DATETIMEOFFSET 	CONSTRAINT [DF_Product_Modified] DEFAULT (GETUTCDATE()) NOT NULL,
	[DeletedDate]			DATETIMEOFFSET	NULL,
    [DeletedBy]				INT   NULL,
    [ModifiedBy]			INT   NULL,
	[CreatedBy]				INT   NULL,
	CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_Product_ProductType] FOREIGN KEY ([TypeId]) REFERENCES [dbo].[ProductTypes] ([Id]),
	CONSTRAINT [FK_Product_ProductGenCategory] FOREIGN KEY ([ProductGenCategoryId]) REFERENCES [dbo].[ProductGenCategory] ([Id]),
	CONSTRAINT [FK_Product_ProductCategory] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[ProductCategory] ([Id]),
	CONSTRAINT [FK_Product_ProductDesigner] FOREIGN KEY ([DesignerId]) REFERENCES [dbo].[ProductDesigners] ([Id]),
	CONSTRAINT [FK_Product_ProductEdits] FOREIGN KEY ([EditId]) REFERENCES [dbo].[ProductEdits] ([Id]),
	--CONSTRAINT [FK_Activity_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([ID]), ProductEdits
	--CONSTRAINT [FK_Activity_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([ID]),
	--CONSTRAINT [FK_Activity_DeletedBy_User] FOREIGN KEY ([DeletedBy]) REFERENCES [dbo].[Users] ([Id]),
 --   CONSTRAINT [FK_Activity_CreatedBy_User] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
 --   CONSTRAINT [FK_Activity_ModifiedBy_User] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id]),
	--CONSTRAINT [FK_Activity_ActivityType] FOREIGN KEY ([TypeId]) REFERENCES [dbo].[ActivityType] ([Id]),
)
